# Generated by Django 3.2.22 on 2023-10-22 09:53

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=core.models.NameField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=core.models.NameField(max_length=255),
        ),
    ]
